*Jun-UFFIOpenGL
asByteArray16f
	^ (ByteArray basicNew: 64)
		floatAt: 1 put: a;
		floatAt: 5 put: b;
		floatAt: 9 put: c;
		floatAt: 13 put: p;
		floatAt: 17 put: d;
		floatAt: 21 put: e;
		floatAt: 25 put: f;
		floatAt: 29 put: q;
		floatAt: 33 put: g;
		floatAt: 37 put: h;
		floatAt: 41 put: i;
		floatAt: 45 put: r;
		floatAt: 49 put: l;
		floatAt: 53 put: m;
		floatAt: 57 put: n;
		floatAt: 61 put: s;
		yourself