Class {
	#name : #JunAntimony,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunAntimony class >> bondRadius1 [
	^ 1.40
]

{ #category : #accessing }
JunAntimony class >> bondRadius2 [
	^ 1.33
]

{ #category : #accessing }
JunAntimony class >> bondRadius3 [
	^ 1.27
]

{ #category : #accessing }
JunAntimony class >> color [
	^ Color fromHexString: '9E63B5'
]

{ #category : #accessing }
JunAntimony class >> covalentRadius [
	^ 1.39
]

{ #category : #accessing }
JunAntimony class >> group [
	^ 15
]

{ #category : #accessing }
JunAntimony class >> mass [
	^ 121.760
]

{ #category : #accessing }
JunAntimony class >> number [
	^ 51
]

{ #category : #accessing }
JunAntimony class >> period [
	^ 5
]

{ #category : #accessing }
JunAntimony class >> symbol [
	^ 'Sb'
]

{ #category : #accessing }
JunAntimony class >> vanDerWaalsRadius [
	^ 2.06
]
