Class {
	#name : #JunArsenic,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunArsenic class >> bondRadius1 [
	^ 1.21
]

{ #category : #accessing }
JunArsenic class >> bondRadius2 [
	^ 1.14
]

{ #category : #accessing }
JunArsenic class >> bondRadius3 [
	^ 1.06
]

{ #category : #accessing }
JunArsenic class >> color [
	^ Color fromHexString: 'BD80E3'
]

{ #category : #accessing }
JunArsenic class >> covalentRadius [
	^ 1.19
]

{ #category : #accessing }
JunArsenic class >> group [
	^ 15
]

{ #category : #accessing }
JunArsenic class >> mass [
	^ 74.921595
]

{ #category : #accessing }
JunArsenic class >> number [
	^ 33
]

{ #category : #accessing }
JunArsenic class >> period [
	^ 4
]

{ #category : #accessing }
JunArsenic class >> symbol [
	^ 'As'
]

{ #category : #accessing }
JunArsenic class >> vanDerWaalsRadius [
	^ 1.85
]
