Class {
	#name : #JunAluminium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunAluminium class >> bondRadius1 [
	^ 1.26
]

{ #category : #accessing }
JunAluminium class >> bondRadius2 [
	^ 1.13
]

{ #category : #accessing }
JunAluminium class >> bondRadius3 [
	^ 1.11
]

{ #category : #accessing }
JunAluminium class >> color [
	^ Color fromHexString: 'BFA6A6'
]

{ #category : #accessing }
JunAluminium class >> covalentRadius [
	^ 1.21
]

{ #category : #accessing }
JunAluminium class >> group [
	^ 13
]

{ #category : #accessing }
JunAluminium class >> mass [
	^ 26.9815385
]

{ #category : #accessing }
JunAluminium class >> number [
	^ 13
]

{ #category : #accessing }
JunAluminium class >> period [
	^ 3
]

{ #category : #accessing }
JunAluminium class >> symbol [
	^ 'Al'
]

{ #category : #accessing }
JunAluminium class >> vanDerWaalsRadius [
	^ 1.84
]
