Class {
	#name : #JunArgon,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunArgon class >> bondRadius1 [
	^ 0.96
]

{ #category : #accessing }
JunArgon class >> bondRadius2 [
	^ 1.07
]

{ #category : #accessing }
JunArgon class >> bondRadius3 [
	^ 0.96
]

{ #category : #accessing }
JunArgon class >> color [
	^ Color fromHexString: '80D1E3'
]

{ #category : #accessing }
JunArgon class >> covalentRadius [
	^ 1.06
]

{ #category : #accessing }
JunArgon class >> group [
	^ 18
]

{ #category : #accessing }
JunArgon class >> mass [
	^ 39.948
]

{ #category : #accessing }
JunArgon class >> number [
	^ 18
]

{ #category : #accessing }
JunArgon class >> period [
	^ 3
]

{ #category : #accessing }
JunArgon class >> symbol [
	^ 'Ar'
]

{ #category : #accessing }
JunArgon class >> vanDerWaalsRadius [
	^ 1.88
]
