Class {
	#name : #JunBeryllium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunBeryllium class >> bondRadius1 [
	^ 1.02
]

{ #category : #accessing }
JunBeryllium class >> bondRadius2 [
	^ 0.90
]

{ #category : #accessing }
JunBeryllium class >> bondRadius3 [
	^ 0.85
]

{ #category : #accessing }
JunBeryllium class >> color [
	^ Color fromHexString: 'C2FF00'
]

{ #category : #accessing }
JunBeryllium class >> covalentRadius [
	^ 0.96
]

{ #category : #accessing }
JunBeryllium class >> group [
	^ 2
]

{ #category : #accessing }
JunBeryllium class >> mass [
	^ 9.0121831
]

{ #category : #accessing }
JunBeryllium class >> number [
	^ 4
]

{ #category : #accessing }
JunBeryllium class >> period [
	^ 2
]

{ #category : #accessing }
JunBeryllium class >> symbol [
	^ 'Be'
]

{ #category : #accessing }
JunBeryllium class >> vanDerWaalsRadius [
	^ 1.53
]
