Class {
	#name : #JunBoron,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunBoron class >> bondRadius1 [
	^ 0.85
]

{ #category : #accessing }
JunBoron class >> bondRadius2 [
	^ 0.78
]

{ #category : #accessing }
JunBoron class >> bondRadius3 [
	^ 0.73
]

{ #category : #accessing }
JunBoron class >> color [
	^ Color fromHexString: 'FFB5B5'
]

{ #category : #accessing }
JunBoron class >> covalentRadius [
	^ 0.84
]

{ #category : #accessing }
JunBoron class >> group [
	^ 13
]

{ #category : #accessing }
JunBoron class >> mass [
	^ 10.81
]

{ #category : #accessing }
JunBoron class >> number [
	^ 5
]

{ #category : #accessing }
JunBoron class >> period [
	^ 2
]

{ #category : #accessing }
JunBoron class >> symbol [
	^ 'B'
]

{ #category : #accessing }
JunBoron class >> vanDerWaalsRadius [
	^ 1.92
]
