Class {
	#name : #JunBromine,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunBromine class >> bondRadius1 [
	^ 1.14
]

{ #category : #accessing }
JunBromine class >> bondRadius2 [
	^ 1.09
]

{ #category : #accessing }
JunBromine class >> bondRadius3 [
	^ 1.10
]

{ #category : #accessing }
JunBromine class >> color [
	^ Color fromHexString: 'A62929'
]

{ #category : #accessing }
JunBromine class >> covalentRadius [
	^ 1.20
]

{ #category : #accessing }
JunBromine class >> group [
	^ 17
]

{ #category : #accessing }
JunBromine class >> mass [
	^ 79.904
]

{ #category : #accessing }
JunBromine class >> number [
	^ 35
]

{ #category : #accessing }
JunBromine class >> period [
	^ 4
]

{ #category : #accessing }
JunBromine class >> symbol [
	^ 'Br'
]

{ #category : #accessing }
JunBromine class >> vanDerWaalsRadius [
	^ 1.85
]
