Class {
	#name : #JunCalcium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunCalcium class >> bondRadius1 [
	^ 1.71
]

{ #category : #accessing }
JunCalcium class >> bondRadius2 [
	^ 1.44
]

{ #category : #accessing }
JunCalcium class >> bondRadius3 [
	^ 1.33
]

{ #category : #accessing }
JunCalcium class >> color [
	^ Color fromHexString: '3DFF00'
]

{ #category : #accessing }
JunCalcium class >> covalentRadius [
	^ 1.76
]

{ #category : #accessing }
JunCalcium class >> group [
	^ 2
]

{ #category : #accessing }
JunCalcium class >> mass [
	^ 40.078
]

{ #category : #accessing }
JunCalcium class >> number [
	^ 20
]

{ #category : #accessing }
JunCalcium class >> period [
	^ 4
]

{ #category : #accessing }
JunCalcium class >> symbol [
	^ 'Ca'
]

{ #category : #accessing }
JunCalcium class >> vanDerWaalsRadius [
	^ 2.31
]
