Class {
	#name : #JunCadmium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunCadmium class >> bondRadius1 [
	^ 1.36
]

{ #category : #accessing }
JunCadmium class >> bondRadius2 [
	^ 1.44
]

{ #category : #accessing }
JunCadmium class >> bondRadius3 [
	^ 0.0
]

{ #category : #accessing }
JunCadmium class >> color [
	^ Color fromHexString: 'FFD98F'
]

{ #category : #accessing }
JunCadmium class >> covalentRadius [
	^ 1.44
]

{ #category : #accessing }
JunCadmium class >> group [
	^ 12
]

{ #category : #accessing }
JunCadmium class >> mass [
	^ 112.414
]

{ #category : #accessing }
JunCadmium class >> number [
	^ 48
]

{ #category : #accessing }
JunCadmium class >> period [
	^ 5
]

{ #category : #accessing }
JunCadmium class >> symbol [
	^ 'Cd'
]

{ #category : #accessing }
JunCadmium class >> vanDerWaalsRadius [
	^ 1.58
]
