Class {
	#name : #JunCobalt,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunCobalt class >> bondRadius1 [
	^ 1.11
]

{ #category : #accessing }
JunCobalt class >> bondRadius2 [
	^ 1.03
]

{ #category : #accessing }
JunCobalt class >> bondRadius3 [
	^ 0.96
]

{ #category : #accessing }
JunCobalt class >> color [
	^ Color fromHexString: 'F090A0'
]

{ #category : #accessing }
JunCobalt class >> covalentRadius [
	^ 1.26
]

{ #category : #accessing }
JunCobalt class >> group [
	^ 9
]

{ #category : #accessing }
JunCobalt class >> mass [
	^ 58.933194
]

{ #category : #accessing }
JunCobalt class >> number [
	^ 27
]

{ #category : #accessing }
JunCobalt class >> period [
	^ 4
]

{ #category : #accessing }
JunCobalt class >> symbol [
	^ 'Co'
]

{ #category : #accessing }
JunCobalt class >> vanDerWaalsRadius [
	^ 1.92
]
