Class {
	#name : #JunChromium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunChromium class >> bondRadius1 [
	^ 1.22
]

{ #category : #accessing }
JunChromium class >> bondRadius2 [
	^ 1.11
]

{ #category : #accessing }
JunChromium class >> bondRadius3 [
	^ 1.03
]

{ #category : #accessing }
JunChromium class >> color [
	^ Color fromHexString: '8A99C7'
]

{ #category : #accessing }
JunChromium class >> covalentRadius [
	^ 1.39
]

{ #category : #accessing }
JunChromium class >> group [
	^ 6
]

{ #category : #accessing }
JunChromium class >> mass [
	^ 51.9961
]

{ #category : #accessing }
JunChromium class >> number [
	^ 24
]

{ #category : #accessing }
JunChromium class >> period [
	^ 4
]

{ #category : #accessing }
JunChromium class >> symbol [
	^ 'Cr'
]

{ #category : #accessing }
JunChromium class >> vanDerWaalsRadius [
	^ 1.89
]
