Class {
	#name : #JunChlorine,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunChlorine class >> bondRadius1 [
	^ 0.99
]

{ #category : #accessing }
JunChlorine class >> bondRadius2 [
	^ 0.95
]

{ #category : #accessing }
JunChlorine class >> bondRadius3 [
	^ 0.93
]

{ #category : #accessing }
JunChlorine class >> color [
	^ Color fromHexString: '1FF01F'
]

{ #category : #accessing }
JunChlorine class >> covalentRadius [
	^ 1.02
]

{ #category : #accessing }
JunChlorine class >> group [
	^ 17
]

{ #category : #accessing }
JunChlorine class >> mass [
	^ 35.45
]

{ #category : #accessing }
JunChlorine class >> number [
	^ 17
]

{ #category : #accessing }
JunChlorine class >> period [
	^ 3
]

{ #category : #accessing }
JunChlorine class >> symbol [
	^ 'Cl'
]

{ #category : #accessing }
JunChlorine class >> vanDerWaalsRadius [
	^ 1.75
]
