Class {
	#name : #JunCupper,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunCupper class >> bondRadius1 [
	^ 1.12
]

{ #category : #accessing }
JunCupper class >> bondRadius2 [
	^ 1.15
]

{ #category : #accessing }
JunCupper class >> bondRadius3 [
	^ 1.20
]

{ #category : #accessing }
JunCupper class >> color [
	^ Color fromHexString: 'C88033'
]

{ #category : #accessing }
JunCupper class >> covalentRadius [
	^ 1.32
]

{ #category : #accessing }
JunCupper class >> group [
	^ 11
]

{ #category : #accessing }
JunCupper class >> mass [
	^ 63.546
]

{ #category : #accessing }
JunCupper class >> number [
	^ 29
]

{ #category : #accessing }
JunCupper class >> period [
	^ 4
]

{ #category : #accessing }
JunCupper class >> symbol [
	^ 'Cu'
]

{ #category : #accessing }
JunCupper class >> vanDerWaalsRadius [
	^ 1.40
]
