Class {
	#name : #JunFluorine,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunFluorine class >> bondRadius1 [
	^ 0.64
]

{ #category : #accessing }
JunFluorine class >> bondRadius2 [
	^ 0.59
]

{ #category : #accessing }
JunFluorine class >> bondRadius3 [
	^ 0.53
]

{ #category : #accessing }
JunFluorine class >> color [
	^ Color fromHexString: '90E050'
]

{ #category : #accessing }
JunFluorine class >> covalentRadius [
	^ 0.57
]

{ #category : #accessing }
JunFluorine class >> group [
	^ 17
]

{ #category : #accessing }
JunFluorine class >> mass [
	^ 18.998403163
]

{ #category : #accessing }
JunFluorine class >> number [
	^ 9
]

{ #category : #accessing }
JunFluorine class >> period [
	^ 2
]

{ #category : #accessing }
JunFluorine class >> symbol [
	^ 'F'
]

{ #category : #accessing }
JunFluorine class >> vanDerWaalsRadius [
	^ 1.35
]
