Class {
	#name : #JunGermanium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunGermanium class >> bondRadius1 [
	^ 1.24
]

{ #category : #accessing }
JunGermanium class >> bondRadius2 [
	^ 1.17
]

{ #category : #accessing }
JunGermanium class >> bondRadius3 [
	^ 1.21
]

{ #category : #accessing }
JunGermanium class >> color [
	^ Color fromHexString: '668F8F'
]

{ #category : #accessing }
JunGermanium class >> covalentRadius [
	^ 1.20
]

{ #category : #accessing }
JunGermanium class >> group [
	^ 14
]

{ #category : #accessing }
JunGermanium class >> mass [
	^ 72.630
]

{ #category : #accessing }
JunGermanium class >> number [
	^ 32
]

{ #category : #accessing }
JunGermanium class >> period [
	^ 4
]

{ #category : #accessing }
JunGermanium class >> symbol [
	^ 'Ge'
]

{ #category : #accessing }
JunGermanium class >> vanDerWaalsRadius [
	^ 2.11
]
