Class {
	#name : #JunGallium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunGallium class >> bondRadius1 [
	^ 1.24
]

{ #category : #accessing }
JunGallium class >> bondRadius2 [
	^ 1.17
]

{ #category : #accessing }
JunGallium class >> bondRadius3 [
	^ 1.21
]

{ #category : #accessing }
JunGallium class >> color [
	^ Color fromHexString: 'C28F8F'
]

{ #category : #accessing }
JunGallium class >> covalentRadius [
	^ 1.22
]

{ #category : #accessing }
JunGallium class >> group [
	^ 13
]

{ #category : #accessing }
JunGallium class >> mass [
	^ 69.723
]

{ #category : #accessing }
JunGallium class >> number [
	^ 31
]

{ #category : #accessing }
JunGallium class >> period [
	^ 4
]

{ #category : #accessing }
JunGallium class >> symbol [
	^ 'Ga'
]

{ #category : #accessing }
JunGallium class >> vanDerWaalsRadius [
	^ 1.87
]
