Class {
	#name : #JunHydrogen,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunHydrogen class >> bondRadius1 [
	^ 0.32
]

{ #category : #accessing }
JunHydrogen class >> bondRadius2 [
	^ 0.0
]

{ #category : #accessing }
JunHydrogen class >> bondRadius3 [
	^ 0.0
]

{ #category : #accessing }
JunHydrogen class >> color [
	^ Color fromHexString: 'FFFFFF'
]

{ #category : #accessing }
JunHydrogen class >> covalentRadius [
	^ 0.31
]

{ #category : #accessing }
JunHydrogen class >> group [
	^ 1
]

{ #category : #accessing }
JunHydrogen class >> mass [
	^ 1.008
]

{ #category : #accessing }
JunHydrogen class >> number [
	^ 1
]

{ #category : #accessing }
JunHydrogen class >> period [
	^ 1
]

{ #category : #accessing }
JunHydrogen class >> symbol [
	^ 'H'
]

{ #category : #accessing }
JunHydrogen class >> vanDerWaalsRadius [
	^ 1.2
]
