Class {
	#name : #JunHelium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunHelium class >> bondRadius1 [
	^ 0.46
]

{ #category : #accessing }
JunHelium class >> bondRadius2 [
	^ 0.0
]

{ #category : #accessing }
JunHelium class >> bondRadius3 [
	^ 0.0
]

{ #category : #accessing }
JunHelium class >> color [
	^ Color fromHexString: 'D9FFFF'
]

{ #category : #accessing }
JunHelium class >> covalentRadius [
	^ 0.28
]

{ #category : #accessing }
JunHelium class >> group [
	^ 18
]

{ #category : #accessing }
JunHelium class >> mass [
	^ 4.002602
]

{ #category : #accessing }
JunHelium class >> number [
	^ 2
]

{ #category : #accessing }
JunHelium class >> period [
	^ 1
]

{ #category : #accessing }
JunHelium class >> symbol [
	^ 'He'
]

{ #category : #accessing }
JunHelium class >> vanDerWaalsRadius [
	^ 1.4
]
