Class {
	#name : #JunIron,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunIron class >> bondRadius1 [
	^ 1.16
]

{ #category : #accessing }
JunIron class >> bondRadius2 [
	^ 1.09
]

{ #category : #accessing }
JunIron class >> bondRadius3 [
	^ 1.02
]

{ #category : #accessing }
JunIron class >> color [
	^ Color fromHexString: 'E06633'
]

{ #category : #accessing }
JunIron class >> covalentRadius [
	^ 1.32
]

{ #category : #accessing }
JunIron class >> group [
	^ 8
]

{ #category : #accessing }
JunIron class >> mass [
	^ 55.845
]

{ #category : #accessing }
JunIron class >> number [
	^ 26
]

{ #category : #accessing }
JunIron class >> period [
	^ 4
]

{ #category : #accessing }
JunIron class >> symbol [
	^ 'Fe'
]

{ #category : #accessing }
JunIron class >> vanDerWaalsRadius [
	^ 1.94
]
