Class {
	#name : #JunIodine,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunIodine class >> bondRadius1 [
	^ 1.33
]

{ #category : #accessing }
JunIodine class >> bondRadius2 [
	^ 1.29
]

{ #category : #accessing }
JunIodine class >> bondRadius3 [
	^ 1.25
]

{ #category : #accessing }
JunIodine class >> color [
	^ Color fromHexString: '940094'
]

{ #category : #accessing }
JunIodine class >> covalentRadius [
	^ 1.39
]

{ #category : #accessing }
JunIodine class >> group [
	^ 17
]

{ #category : #accessing }
JunIodine class >> mass [
	^ 126.90447
]

{ #category : #accessing }
JunIodine class >> number [
	^ 53
]

{ #category : #accessing }
JunIodine class >> period [
	^ 5
]

{ #category : #accessing }
JunIodine class >> symbol [
	^ 'I'
]

{ #category : #accessing }
JunIodine class >> vanDerWaalsRadius [
	^ 1.98
]
