Class {
	#name : #JunIndium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunIndium class >> bondRadius1 [
	^ 1.42
]

{ #category : #accessing }
JunIndium class >> bondRadius2 [
	^ 1.36
]

{ #category : #accessing }
JunIndium class >> bondRadius3 [
	^ 1.46
]

{ #category : #accessing }
JunIndium class >> color [
	^ Color fromHexString: 'A67573'
]

{ #category : #accessing }
JunIndium class >> covalentRadius [
	^ 1.42
]

{ #category : #accessing }
JunIndium class >> group [
	^ 13
]

{ #category : #accessing }
JunIndium class >> mass [
	^ 114.818
]

{ #category : #accessing }
JunIndium class >> number [
	^ 49
]

{ #category : #accessing }
JunIndium class >> period [
	^ 5
]

{ #category : #accessing }
JunIndium class >> symbol [
	^ 'In'
]

{ #category : #accessing }
JunIndium class >> vanDerWaalsRadius [
	^ 1.93
]
