Class {
	#name : #JunKrypton,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunKrypton class >> bondRadius1 [
	^ 1.17
]

{ #category : #accessing }
JunKrypton class >> bondRadius2 [
	^ 1.21
]

{ #category : #accessing }
JunKrypton class >> bondRadius3 [
	^ 1.08
]

{ #category : #accessing }
JunKrypton class >> color [
	^ Color fromHexString: '5CB8D1'
]

{ #category : #accessing }
JunKrypton class >> covalentRadius [
	^ 1.16
]

{ #category : #accessing }
JunKrypton class >> group [
	^ 18
]

{ #category : #accessing }
JunKrypton class >> mass [
	^ 83.798
]

{ #category : #accessing }
JunKrypton class >> number [
	^ 36
]

{ #category : #accessing }
JunKrypton class >> period [
	^ 4
]

{ #category : #accessing }
JunKrypton class >> symbol [
	^ 'Kr'
]

{ #category : #accessing }
JunKrypton class >> vanDerWaalsRadius [
	^ 2.02
]
