Class {
	#name : #JunLithium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunLithium class >> bondRadius1 [
	^ 1.33
]

{ #category : #accessing }
JunLithium class >> bondRadius2 [
	^ 1.24
]

{ #category : #accessing }
JunLithium class >> bondRadius3 [
	^ 0.0
]

{ #category : #accessing }
JunLithium class >> color [
	^ Color fromHexString: 'CC80FF'
]

{ #category : #accessing }
JunLithium class >> covalentRadius [
	^ 1.28
]

{ #category : #accessing }
JunLithium class >> group [
	^ 1
]

{ #category : #accessing }
JunLithium class >> mass [
	^ 6.94
]

{ #category : #accessing }
JunLithium class >> number [
	^ 3
]

{ #category : #accessing }
JunLithium class >> period [
	^ 2
]

{ #category : #accessing }
JunLithium class >> symbol [
	^ 'Li'
]

{ #category : #accessing }
JunLithium class >> vanDerWaalsRadius [
	^ 1.82
]
