Class {
	#name : #JunMolybdenum,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunMolybdenum class >> bondRadius1 [
	^ 1.38
]

{ #category : #accessing }
JunMolybdenum class >> bondRadius2 [
	^ 1.21
]

{ #category : #accessing }
JunMolybdenum class >> bondRadius3 [
	^ 1.13
]

{ #category : #accessing }
JunMolybdenum class >> color [
	^ Color fromHexString: '54B5B5'
]

{ #category : #accessing }
JunMolybdenum class >> covalentRadius [
	^ 1.54
]

{ #category : #accessing }
JunMolybdenum class >> group [
	^ 6
]

{ #category : #accessing }
JunMolybdenum class >> mass [
	^ 95.95
]

{ #category : #accessing }
JunMolybdenum class >> number [
	^ 42
]

{ #category : #accessing }
JunMolybdenum class >> period [
		^ 5
]

{ #category : #accessing }
JunMolybdenum class >> symbol [
	^ 'Mo'
]

{ #category : #accessing }
JunMolybdenum class >> vanDerWaalsRadius [
	^ 2.09
]
