Class {
	#name : #JunMagnesium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunMagnesium class >> bondRadius1 [
	^ 1.39
]

{ #category : #accessing }
JunMagnesium class >> bondRadius2 [
	^ 1.36
]

{ #category : #accessing }
JunMagnesium class >> bondRadius3 [
	^ 1.27
]

{ #category : #accessing }
JunMagnesium class >> color [
	^ Color fromHexString: '8AFF00'
]

{ #category : #accessing }
JunMagnesium class >> covalentRadius [
	^ 1.41
]

{ #category : #accessing }
JunMagnesium class >> group [
	^ 2
]

{ #category : #accessing }
JunMagnesium class >> mass [
	^ 24.305
]

{ #category : #accessing }
JunMagnesium class >> number [
	^ 12
]

{ #category : #accessing }
JunMagnesium class >> period [
	^ 3
]

{ #category : #accessing }
JunMagnesium class >> symbol [
	^ 'Mg'
]

{ #category : #accessing }
JunMagnesium class >> vanDerWaalsRadius [
	^ 1.73
]
