Class {
	#name : #JunManganese,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunManganese class >> bondRadius1 [
	^ 1.19
]

{ #category : #accessing }
JunManganese class >> bondRadius2 [
	^ 1.05
]

{ #category : #accessing }
JunManganese class >> bondRadius3 [
	^ 1.03
]

{ #category : #accessing }
JunManganese class >> color [
	^ Color fromHexString: '9C7AC7'
]

{ #category : #accessing }
JunManganese class >> covalentRadius [
	^ 1.39
]

{ #category : #accessing }
JunManganese class >> group [
	^ 7
]

{ #category : #accessing }
JunManganese class >> mass [
	^ 54.938044
]

{ #category : #accessing }
JunManganese class >> number [
	^ 25
]

{ #category : #accessing }
JunManganese class >> period [
	^ 4
]

{ #category : #accessing }
JunManganese class >> symbol [
	^ 'Mn'
]

{ #category : #accessing }
JunManganese class >> vanDerWaalsRadius [
	^ 1.97
]
