Class {
	#name : #JunNiobium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunNiobium class >> bondRadius1 [
	^ 1.47
]

{ #category : #accessing }
JunNiobium class >> bondRadius2 [
	^ 1.25
]

{ #category : #accessing }
JunNiobium class >> bondRadius3 [
	^ 1.16
]

{ #category : #accessing }
JunNiobium class >> color [
	^ Color fromHexString: '73C2C9'
]

{ #category : #accessing }
JunNiobium class >> covalentRadius [
	^ 1.64
]

{ #category : #accessing }
JunNiobium class >> group [
	^ 5
]

{ #category : #accessing }
JunNiobium class >> mass [
	^ 92.90637
]

{ #category : #accessing }
JunNiobium class >> number [
	^ 41
]

{ #category : #accessing }
JunNiobium class >> period [
	^ 5
]

{ #category : #accessing }
JunNiobium class >> symbol [
	^ 'Nb'
]

{ #category : #accessing }
JunNiobium class >> vanDerWaalsRadius [
	^ 2.07
]
