Class {
	#name : #JunNitrogen,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunNitrogen class >> bondRadius1 [
	^ 0.71
]

{ #category : #accessing }
JunNitrogen class >> bondRadius2 [
	^ 0.60
]

{ #category : #accessing }
JunNitrogen class >> bondRadius3 [
	^ 0.54
]

{ #category : #accessing }
JunNitrogen class >> color [
	^ Color fromHexString: '3050F8'
]

{ #category : #accessing }
JunNitrogen class >> covalentRadius [
	^ 0.71
]

{ #category : #accessing }
JunNitrogen class >> group [
	^ 15
]

{ #category : #accessing }
JunNitrogen class >> mass [
	^ 14.007
]

{ #category : #accessing }
JunNitrogen class >> number [
	^ 7
]

{ #category : #accessing }
JunNitrogen class >> period [
	^ 2
]

{ #category : #accessing }
JunNitrogen class >> symbol [
	^ 'N'
]

{ #category : #accessing }
JunNitrogen class >> vanDerWaalsRadius [
	^ 1.55
]
