Class {
	#name : #JunNickel,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunNickel class >> bondRadius1 [
	^ 1.10
]

{ #category : #accessing }
JunNickel class >> bondRadius2 [
	^ 1.01
]

{ #category : #accessing }
JunNickel class >> bondRadius3 [
	^ 1.01
]

{ #category : #accessing }
JunNickel class >> color [
	^ Color fromHexString: '50D050'
]

{ #category : #accessing }
JunNickel class >> covalentRadius [
	^ 1.24
]

{ #category : #accessing }
JunNickel class >> group [
	^ 10
]

{ #category : #accessing }
JunNickel class >> mass [
	^ 58.6934
]

{ #category : #accessing }
JunNickel class >> number [
	^ 28
]

{ #category : #accessing }
JunNickel class >> period [
	^ 4
]

{ #category : #accessing }
JunNickel class >> symbol [
	^ 'Ni'
]

{ #category : #accessing }
JunNickel class >> vanDerWaalsRadius [
	^ 1.63
]
