Class {
	#name : #JunNeon,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunNeon class >> bondRadius1 [
	^ 0.67
]

{ #category : #accessing }
JunNeon class >> bondRadius2 [
	^ 0.96
]

{ #category : #accessing }
JunNeon class >> bondRadius3 [
	^ 0.0
]

{ #category : #accessing }
JunNeon class >> color [
	^ Color fromHexString: 'B3E3F5'
]

{ #category : #accessing }
JunNeon class >> covalentRadius [
	^ 0.58
]

{ #category : #accessing }
JunNeon class >> group [
	^ 18
]

{ #category : #accessing }
JunNeon class >> mass [
	^ 20.1797
]

{ #category : #accessing }
JunNeon class >> number [
	^ 10
]

{ #category : #accessing }
JunNeon class >> period [
	^ 2
]

{ #category : #accessing }
JunNeon class >> symbol [
	^ 'Ne'
]

{ #category : #accessing }
JunNeon class >> vanDerWaalsRadius [
	^ 1.54
]
