Class {
	#name : #JunPalladium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunPalladium class >> bondRadius1 [
	^ 1.20
]

{ #category : #accessing }
JunPalladium class >> bondRadius2 [
	^ 1.17
]

{ #category : #accessing }
JunPalladium class >> bondRadius3 [
	^ 1.12
]

{ #category : #accessing }
JunPalladium class >> color [
	^ Color fromHexString: '006985'
]

{ #category : #accessing }
JunPalladium class >> covalentRadius [
	^ 1.39
]

{ #category : #accessing }
JunPalladium class >> group [
	^ 10
]

{ #category : #accessing }
JunPalladium class >> mass [
	^ 106.42
]

{ #category : #accessing }
JunPalladium class >> number [
	^ 46
]

{ #category : #accessing }
JunPalladium class >> period [
	^ 5
]

{ #category : #accessing }
JunPalladium class >> symbol [
	^ 'Pd'
]

{ #category : #accessing }
JunPalladium class >> vanDerWaalsRadius [
	^ 1.63
]
