Class {
	#name : #JunPhosphorus,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunPhosphorus class >> bondRadius1 [
	^ 1.11
]

{ #category : #accessing }
JunPhosphorus class >> bondRadius2 [
	^ 1.02
]

{ #category : #accessing }
JunPhosphorus class >> bondRadius3 [
	^ 0.94
]

{ #category : #accessing }
JunPhosphorus class >> color [
	^ Color fromHexString: 'FF8000'
]

{ #category : #accessing }
JunPhosphorus class >> covalentRadius [
	^ 1.07
]

{ #category : #accessing }
JunPhosphorus class >> group [
	^ 15
]

{ #category : #accessing }
JunPhosphorus class >> mass [
	^ 30.973761998
]

{ #category : #accessing }
JunPhosphorus class >> number [
	^ 15
]

{ #category : #accessing }
JunPhosphorus class >> period [
	^ 3
]

{ #category : #accessing }
JunPhosphorus class >> symbol [
	^ 'P'
]

{ #category : #accessing }
JunPhosphorus class >> vanDerWaalsRadius [
	^ 1.80
]
