Class {
	#name : #JunPotassium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunPotassium class >> bondRadius1 [
	^ 1.96
]

{ #category : #accessing }
JunPotassium class >> bondRadius2 [
	^ 1.93
]

{ #category : #accessing }
JunPotassium class >> bondRadius3 [
	^ 0.0
]

{ #category : #accessing }
JunPotassium class >> color [
	^ Color fromHexString: '8F40D4'
]

{ #category : #accessing }
JunPotassium class >> covalentRadius [
	^ 2.03
]

{ #category : #accessing }
JunPotassium class >> group [
	^ 1
]

{ #category : #accessing }
JunPotassium class >> mass [
	^ 39.0983
]

{ #category : #accessing }
JunPotassium class >> number [
	^ 19
]

{ #category : #accessing }
JunPotassium class >> period [
	^ 4
]

{ #category : #accessing }
JunPotassium class >> symbol [
	^ 'K'
]

{ #category : #accessing }
JunPotassium class >> vanDerWaalsRadius [
	^ 2.75
]
