Class {
	#name : #JunRubidium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunRubidium class >> bondRadius1 [
	^ 2.10
]

{ #category : #accessing }
JunRubidium class >> bondRadius2 [
	^ 2.02
]

{ #category : #accessing }
JunRubidium class >> bondRadius3 [
	^ 0.0
]

{ #category : #accessing }
JunRubidium class >> color [
	^ Color fromHexString: '702EB0'
]

{ #category : #accessing }
JunRubidium class >> covalentRadius [
	^ 2.20
]

{ #category : #accessing }
JunRubidium class >> group [
		^ 1
]

{ #category : #accessing }
JunRubidium class >> mass [
	^ 85.4678
]

{ #category : #accessing }
JunRubidium class >> number [
	^ 37
]

{ #category : #accessing }
JunRubidium class >> period [
	^ 5
]

{ #category : #accessing }
JunRubidium class >> symbol [
	^ 'Rb'
]

{ #category : #accessing }
JunRubidium class >> vanDerWaalsRadius [
	^ 3.03
]
