Class {
	#name : #JunRhodium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunRhodium class >> bondRadius1 [
	^ 1.25
]

{ #category : #accessing }
JunRhodium class >> bondRadius2 [
	^ 1.10
]

{ #category : #accessing }
JunRhodium class >> bondRadius3 [
	^ 1.06
]

{ #category : #accessing }
JunRhodium class >> color [
	^ Color fromHexString: '0A7D8C'
]

{ #category : #accessing }
JunRhodium class >> covalentRadius [
	^ 1.42
]

{ #category : #accessing }
JunRhodium class >> group [
	^ 9
]

{ #category : #accessing }
JunRhodium class >> mass [
	^ 102.90550
]

{ #category : #accessing }
JunRhodium class >> number [
	^ 45
]

{ #category : #accessing }
JunRhodium class >> period [
	^ 5
]

{ #category : #accessing }
JunRhodium class >> symbol [
	^ 'Rh'
]

{ #category : #accessing }
JunRhodium class >> vanDerWaalsRadius [
	^ 1.95
]
