Class {
	#name : #JunRuthenium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunRuthenium class >> bondRadius1 [
	^ 1.25
]

{ #category : #accessing }
JunRuthenium class >> bondRadius2 [
	^ 1.14
]

{ #category : #accessing }
JunRuthenium class >> bondRadius3 [
	^ 1.03
]

{ #category : #accessing }
JunRuthenium class >> color [
	^ Color fromHexString: '248F8F'
]

{ #category : #accessing }
JunRuthenium class >> covalentRadius [
	^ 1.46
]

{ #category : #accessing }
JunRuthenium class >> group [
	^ 8
]

{ #category : #accessing }
JunRuthenium class >> mass [
	^ 101.07
]

{ #category : #accessing }
JunRuthenium class >> number [
	^ 44
]

{ #category : #accessing }
JunRuthenium class >> period [
	^ 5
]

{ #category : #accessing }
JunRuthenium class >> symbol [
	^ 'Ru'
]

{ #category : #accessing }
JunRuthenium class >> vanDerWaalsRadius [
	^ 2.07
]
