Class {
	#name : #JunSodium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunSodium class >> bondRadius1 [
	^ 1.55
]

{ #category : #accessing }
JunSodium class >> bondRadius2 [
	^ 1.60
]

{ #category : #accessing }
JunSodium class >> bondRadius3 [
	^ 0.0
]

{ #category : #accessing }
JunSodium class >> color [
	^ Color fromHexString: 'AB5CF2'
]

{ #category : #accessing }
JunSodium class >> covalentRadius [
	^ 1.66
]

{ #category : #accessing }
JunSodium class >> group [
		^ 1
]

{ #category : #accessing }
JunSodium class >> mass [
	^ 22.98976928
]

{ #category : #accessing }
JunSodium class >> number [
	^ 11
]

{ #category : #accessing }
JunSodium class >> period [
	^ 3
]

{ #category : #accessing }
JunSodium class >> symbol [
	^ 'Na'
]

{ #category : #accessing }
JunSodium class >> vanDerWaalsRadius [
	^ 2.27
]
