Class {
	#name : #JunScandium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunScandium class >> bondRadius1 [
	^ 1.48
]

{ #category : #accessing }
JunScandium class >> bondRadius2 [
	^ 1.16
]

{ #category : #accessing }
JunScandium class >> bondRadius3 [
	^ 1.14
]

{ #category : #accessing }
JunScandium class >> color [
	^ Color fromHexString: 'E6E6E6'
]

{ #category : #accessing }
JunScandium class >> covalentRadius [
	^ 1.70
]

{ #category : #accessing }
JunScandium class >> group [
	^ 3
]

{ #category : #accessing }
JunScandium class >> mass [
	^ 44.955908
]

{ #category : #accessing }
JunScandium class >> number [
	^ 21
]

{ #category : #accessing }
JunScandium class >> period [
	^ 4
]

{ #category : #accessing }
JunScandium class >> symbol [
	^ 'Sc'
]

{ #category : #accessing }
JunScandium class >> vanDerWaalsRadius [
	^ 2.11
]
