Class {
	#name : #JunStrontium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunStrontium class >> bondRadius1 [
	^ 1.85
]

{ #category : #accessing }
JunStrontium class >> bondRadius2 [
	^ 1.57
]

{ #category : #accessing }
JunStrontium class >> bondRadius3 [
	^ 1.39
]

{ #category : #accessing }
JunStrontium class >> color [
	^ Color fromHexString: '00FF00'
]

{ #category : #accessing }
JunStrontium class >> covalentRadius [
	^ 1.95
]

{ #category : #accessing }
JunStrontium class >> group [
	^ 2
]

{ #category : #accessing }
JunStrontium class >> mass [
	^ 87.62
]

{ #category : #accessing }
JunStrontium class >> number [
	^ 38
]

{ #category : #accessing }
JunStrontium class >> period [
	^ 5
]

{ #category : #accessing }
JunStrontium class >> symbol [
	^ 'Sr'
]

{ #category : #accessing }
JunStrontium class >> vanDerWaalsRadius [
	^ 2.49
]
