Class {
	#name : #JunSilver,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunSilver class >> bondRadius1 [
	^ 1.28
]

{ #category : #accessing }
JunSilver class >> bondRadius2 [
	^ 1.39
]

{ #category : #accessing }
JunSilver class >> bondRadius3 [
	^ 1.37
]

{ #category : #accessing }
JunSilver class >> color [
	^ Color fromHexString: 'C0C0C0'
]

{ #category : #accessing }
JunSilver class >> covalentRadius [
	^ 1.45
]

{ #category : #accessing }
JunSilver class >> group [
	^ 11
]

{ #category : #accessing }
JunSilver class >> mass [
	^ 107.8682
]

{ #category : #accessing }
JunSilver class >> number [
	^ 47
]

{ #category : #accessing }
JunSilver class >> period [
	^ 5
]

{ #category : #accessing }
JunSilver class >> symbol [
	^ 'Ag'
]

{ #category : #accessing }
JunSilver class >> vanDerWaalsRadius [
	^ 1.72
]
