Class {
	#name : #JunSulfur,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunSulfur class >> bondRadius1 [
	^ 1.03
]

{ #category : #accessing }
JunSulfur class >> bondRadius2 [
	^ 0.94
]

{ #category : #accessing }
JunSulfur class >> bondRadius3 [
	^ 0.95
]

{ #category : #accessing }
JunSulfur class >> color [
	^ Color fromHexString: 'FFFF30'
]

{ #category : #accessing }
JunSulfur class >> covalentRadius [
	^ 1.05
]

{ #category : #accessing }
JunSulfur class >> group [
	^ 16
]

{ #category : #accessing }
JunSulfur class >> mass [
	^ 32.06
]

{ #category : #accessing }
JunSulfur class >> number [
	^ 16
]

{ #category : #accessing }
JunSulfur class >> period [
	^ 3
]

{ #category : #accessing }
JunSulfur class >> symbol [
	^ 'S'
]

{ #category : #accessing }
JunSulfur class >> vanDerWaalsRadius [
	^ 1.80
]
