Class {
	#name : #JunSelenium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunSelenium class >> bondRadius1 [
	^ 1.16
]

{ #category : #accessing }
JunSelenium class >> bondRadius2 [
	^ 1.07
]

{ #category : #accessing }
JunSelenium class >> bondRadius3 [
	^ 1.07
]

{ #category : #accessing }
JunSelenium class >> color [
	^ Color fromHexString: 'FFA100'
]

{ #category : #accessing }
JunSelenium class >> covalentRadius [
	^ 1.20
]

{ #category : #accessing }
JunSelenium class >> group [
	^ 16
]

{ #category : #accessing }
JunSelenium class >> mass [
	^ 78.971
]

{ #category : #accessing }
JunSelenium class >> number [
	^ 34
]

{ #category : #accessing }
JunSelenium class >> period [
	^ 4
]

{ #category : #accessing }
JunSelenium class >> symbol [
	^ 'Se'
]

{ #category : #accessing }
JunSelenium class >> vanDerWaalsRadius [
	^ 1.90
]
