Class {
	#name : #JunSilicon,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunSilicon class >> bondRadius1 [
	^ 1.16
]

{ #category : #accessing }
JunSilicon class >> bondRadius2 [
	^ 1.07
]

{ #category : #accessing }
JunSilicon class >> bondRadius3 [
	^ 1.02
]

{ #category : #accessing }
JunSilicon class >> color [
	^ Color fromHexString: 'F0C8A0'
]

{ #category : #accessing }
JunSilicon class >> covalentRadius [
	^ 1.11
]

{ #category : #accessing }
JunSilicon class >> group [
	^ 14
]

{ #category : #accessing }
JunSilicon class >> mass [
	^ 28.085
]

{ #category : #accessing }
JunSilicon class >> number [
	^ 14
]

{ #category : #accessing }
JunSilicon class >> period [
	^ 3
]

{ #category : #accessing }
JunSilicon class >> symbol [
	^ 'Si'
]

{ #category : #accessing }
JunSilicon class >> vanDerWaalsRadius [
	^ 2.10
]
