Class {
	#name : #JunTitanium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunTitanium class >> bondRadius1 [
	^ 1.36
]

{ #category : #accessing }
JunTitanium class >> bondRadius2 [
	^ 1.17
]

{ #category : #accessing }
JunTitanium class >> bondRadius3 [
	^ 1.08
]

{ #category : #accessing }
JunTitanium class >> color [
	^ Color fromHexString: 'BFC2C7'
]

{ #category : #accessing }
JunTitanium class >> covalentRadius [
	^ 1.60
]

{ #category : #accessing }
JunTitanium class >> group [
	^ 4
]

{ #category : #accessing }
JunTitanium class >> mass [
	^ 47.867
]

{ #category : #accessing }
JunTitanium class >> number [
	^ 22
]

{ #category : #accessing }
JunTitanium class >> period [
	^ 4
]

{ #category : #accessing }
JunTitanium class >> symbol [
	^ 'Ti'
]

{ #category : #accessing }
JunTitanium class >> vanDerWaalsRadius [
	^ 1.87
]
