Class {
	#name : #JunTechnetium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunTechnetium class >> bondRadius1 [
	^ 1.28
]

{ #category : #accessing }
JunTechnetium class >> bondRadius2 [
	^ 1.20
]

{ #category : #accessing }
JunTechnetium class >> bondRadius3 [
	^ 1.10
]

{ #category : #accessing }
JunTechnetium class >> color [
	^ Color fromHexString: '3B9E9E'
]

{ #category : #accessing }
JunTechnetium class >> covalentRadius [
	^ 1.47
]

{ #category : #accessing }
JunTechnetium class >> group [
	^ 7
]

{ #category : #accessing }
JunTechnetium class >> mass [
	^ 98.0
]

{ #category : #accessing }
JunTechnetium class >> number [
	^ 43
]

{ #category : #accessing }
JunTechnetium class >> period [
	^ 5
]

{ #category : #accessing }
JunTechnetium class >> symbol [
	^ 'Tc'
]

{ #category : #accessing }
JunTechnetium class >> vanDerWaalsRadius [
	^ 2.09
]
