Class {
	#name : #JunTin,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunTin class >> bondRadius1 [
	^ 1.40
]

{ #category : #accessing }
JunTin class >> bondRadius2 [
	^ 1.30
]

{ #category : #accessing }
JunTin class >> bondRadius3 [
	^ 1.32
]

{ #category : #accessing }
JunTin class >> color [
	^ Color fromHexString: '668080'
]

{ #category : #accessing }
JunTin class >> covalentRadius [
	^ 1.39
]

{ #category : #accessing }
JunTin class >> group [
	^ 14
]

{ #category : #accessing }
JunTin class >> mass [
	^ 118.710
]

{ #category : #accessing }
JunTin class >> number [
	^ 50
]

{ #category : #accessing }
JunTin class >> period [
	^ 5
]

{ #category : #accessing }
JunTin class >> symbol [
	^ 'Sn'
]

{ #category : #accessing }
JunTin class >> vanDerWaalsRadius [
	^ 2.17
]
