Class {
	#name : #JunTellurium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunTellurium class >> bondRadius1 [
	^ 1.36
]

{ #category : #accessing }
JunTellurium class >> bondRadius2 [
	^ 1.28
]

{ #category : #accessing }
JunTellurium class >> bondRadius3 [
	^ 1.21
]

{ #category : #accessing }
JunTellurium class >> color [
	^ Color fromHexString: 'D47A00'
]

{ #category : #accessing }
JunTellurium class >> covalentRadius [
	^ 1.38
]

{ #category : #accessing }
JunTellurium class >> group [
	^ 16
]

{ #category : #accessing }
JunTellurium class >> mass [
	^ 127.60
]

{ #category : #accessing }
JunTellurium class >> number [
	^ 52
]

{ #category : #accessing }
JunTellurium class >> period [
	^ 5
]

{ #category : #accessing }
JunTellurium class >> symbol [
	^ 'Te'
]

{ #category : #accessing }
JunTellurium class >> vanDerWaalsRadius [
	^ 2.06
]
