Class {
	#name : #JunVanadium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunVanadium class >> bondRadius1 [
	^ 1.34
]

{ #category : #accessing }
JunVanadium class >> bondRadius2 [
	^ 1.12
]

{ #category : #accessing }
JunVanadium class >> bondRadius3 [
	^ 1.06
]

{ #category : #accessing }
JunVanadium class >> color [
	^ Color fromHexString: 'A6A6AB'
]

{ #category : #accessing }
JunVanadium class >> covalentRadius [
	^ 1.53
]

{ #category : #accessing }
JunVanadium class >> group [
	^ 5
]

{ #category : #accessing }
JunVanadium class >> mass [
	^ 50.9415
]

{ #category : #accessing }
JunVanadium class >> number [
	^ 23
]

{ #category : #accessing }
JunVanadium class >> period [
	^ 4
]

{ #category : #accessing }
JunVanadium class >> symbol [
	^ 'V'
]

{ #category : #accessing }
JunVanadium class >> vanDerWaalsRadius [
	^ 1.79
]
