Class {
	#name : #JunXenon,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunXenon class >> bondRadius1 [
	^ 1.31
]

{ #category : #accessing }
JunXenon class >> bondRadius2 [
	^ 1.35
]

{ #category : #accessing }
JunXenon class >> bondRadius3 [
	^ 1.22
]

{ #category : #accessing }
JunXenon class >> color [
	^ Color fromHexString: '429EB0'
]

{ #category : #accessing }
JunXenon class >> covalentRadius [
	^ 1.40
]

{ #category : #accessing }
JunXenon class >> group [
	^ 18
]

{ #category : #accessing }
JunXenon class >> mass [
	^ 131.293
]

{ #category : #accessing }
JunXenon class >> number [
	^ 54
]

{ #category : #accessing }
JunXenon class >> period [
	^ 5
]

{ #category : #accessing }
JunXenon class >> symbol [
	^ 'Xe'
]

{ #category : #accessing }
JunXenon class >> vanDerWaalsRadius [
	^ 2.16
]
