Class {
	#name : #JunYttrium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunYttrium class >> bondRadius1 [
	^ 1.63
]

{ #category : #accessing }
JunYttrium class >> bondRadius2 [
	^ 1.30
]

{ #category : #accessing }
JunYttrium class >> bondRadius3 [
	^ 1.24
]

{ #category : #accessing }
JunYttrium class >> color [
	^ Color fromHexString: '94FFFF'
]

{ #category : #accessing }
JunYttrium class >> covalentRadius [
	^ 1.90
]

{ #category : #accessing }
JunYttrium class >> group [
	^ 3
]

{ #category : #accessing }
JunYttrium class >> mass [
	^ 88.90584
]

{ #category : #accessing }
JunYttrium class >> number [
	^ 39
]

{ #category : #accessing }
JunYttrium class >> period [
	^ 5
]

{ #category : #accessing }
JunYttrium class >> symbol [
	^ 'Y'
]

{ #category : #accessing }
JunYttrium class >> vanDerWaalsRadius [
	^ 2.19
]
