Class {
	#name : #JunZirconium,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunZirconium class >> bondRadius1 [
	^ 1.54
]

{ #category : #accessing }
JunZirconium class >> bondRadius2 [
	^ 1.27
]

{ #category : #accessing }
JunZirconium class >> bondRadius3 [
	^ 1.21
]

{ #category : #accessing }
JunZirconium class >> color [
	^ Color fromHexString: '94E0E0'
]

{ #category : #accessing }
JunZirconium class >> covalentRadius [
	^ 1.75
]

{ #category : #accessing }
JunZirconium class >> group [
	^ 4
]

{ #category : #accessing }
JunZirconium class >> mass [
	^ 91.224
]

{ #category : #accessing }
JunZirconium class >> number [
	^ 40
]

{ #category : #accessing }
JunZirconium class >> period [
	^ 5
]

{ #category : #accessing }
JunZirconium class >> symbol [
	^ 'Zr'
]

{ #category : #accessing }
JunZirconium class >> vanDerWaalsRadius [
	^ 1.86
]
