Class {
	#name : #JunZinc,
	#superclass : #JunAtom,
	#category : 'Jun-Chemistry-Atoms'
}

{ #category : #accessing }
JunZinc class >> bondRadius1 [
	^ 1.18
]

{ #category : #accessing }
JunZinc class >> bondRadius2 [
	^ 1.20
]

{ #category : #accessing }
JunZinc class >> bondRadius3 [
	^ 0.0
]

{ #category : #accessing }
JunZinc class >> color [
	^ Color fromHexString: '7D80B0'
]

{ #category : #accessing }
JunZinc class >> covalentRadius [
	^ 1.22
]

{ #category : #accessing }
JunZinc class >> group [
	^ 12
]

{ #category : #accessing }
JunZinc class >> mass [
	^ 65.38
]

{ #category : #accessing }
JunZinc class >> number [
	^ 30
]

{ #category : #accessing }
JunZinc class >> period [
	^ 4
]

{ #category : #accessing }
JunZinc class >> symbol [
	^ 'Zn'
]

{ #category : #accessing }
JunZinc class >> vanDerWaalsRadius [
	^ 1.39
]
