comparing
= aTransformation
	self class == aTransformation class
		ifFalse: [ ^ false ].
	^ ((((((((((((((a = aTransformation a and: [ b = aTransformation b ]) and: [ c = aTransformation c ])
		and: [ p = aTransformation p ]) and: [ d = aTransformation d ]) and: [ e = aTransformation e ])
		and: [ f = aTransformation f ]) and: [ q = aTransformation q ]) and: [ g = aTransformation g ])
		and: [ h = aTransformation h ]) and: [ i = aTransformation i ]) and: [ r = aTransformation r ])
		and: [ l = aTransformation l ]) and: [ m = aTransformation m ]) and: [ n = aTransformation n ])
		and: [ s = aTransformation s ]