converting
asArray
	| array |
	array := Array new: 16.
	array at: 1 put: a.
	array at: 2 put: b.
	array at: 3 put: c.
	array at: 4 put: p.
	array at: 5 put: d.
	array at: 6 put: e.
	array at: 7 put: f.
	array at: 8 put: q.
	array at: 9 put: g.
	array at: 10 put: h.
	array at: 11 put: i.
	array at: 12 put: r.
	array at: 13 put: l.
	array at: 14 put: m.
	array at: 15 put: n.
	array at: 16 put: s.
	^ array