private
setFromArray: anArray 
	self
		setA: (anArray at: 1);
		setB: (anArray at: 2);
		setC: (anArray at: 3);
		setP: (anArray at: 4).
	self
		setD: (anArray at: 5);
		setE: (anArray at: 6);
		setF: (anArray at: 7);
		setQ: (anArray at: 8).
	self
		setG: (anArray at: 9);
		setH: (anArray at: 10);
		setI: (anArray at: 11);
		setR: (anArray at: 12).
	self
		setL: (anArray at: 13);
		setM: (anArray at: 14);
		setN: (anArray at: 15);
		setS: (anArray at: 16)